pull_request_rules:
  - name: automatically merge Scala Steward PRs on CI success
    conditions:
      - author=scala-steward
      - status-success=Build and Test (ubuntu-latest, 3.7.2, zulu@8)
    actions:
      merge:
        method: merge
