pull_request_rules:
  - name: automatically merge Scala Steward PRs on CI success
    conditions:
      - author=scala-steward
      - status-success=Build and Test (ubuntu-latest, 3.6.4, zulu@8)
      - body~=labels:.*semver-patch.*
    actions:
      merge:
        method: merge
